In [15]:
"""Numpy array basic"""
import numpy as np



Creating array from list


In [16]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

# To create a proper 2D array, all rows must have the same length
array_2d = np.array([[1, 2, 3, 4], [4, 5, 6, 0]])
print(array_2d)

[1 2 3 4 5]
[[1 2 3 4]
 [4 5 6 0]]


Multiplication list vs numpy array

In [ ]:
py_list = [1, 2, 3]
print("Python list multiplication: ", py_list * 2)

np_array = np.array([1, 2, 3])  # element whise multiplication
print("Numpy multiplication: ", np_array * 2)

import time

start = time.time()

py_list = [i * 2 for i in range(10)]
print("\nList operation time: ", time.time() - start)

start = time.time()

np_array = np.arange(10) * 2
print("\n Numpy operation time: ", time.time() - start)